name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@d8f6715049803e982ee5ff501b6b9b7d5deeb09b # v3
        with:
          github_user_name: fatmakahveci
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@5859b4ea7efe6b470a5b19c570460eae9323aefc # v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
